
[worldgen]

	#.
	#Modify Create's impact on your terrain
	[worldgen.v2]
		#.
		#.
		#Prevents all worldgen added by Create: Dreams n' Desires from taking effect
		disableWorldGen = false

		[worldgen.v2.dolomite_blob]
			#.
			#Range: > 0
			clusterSize = 64
			#.
			#Amount of clusters generated per Chunk.
			#  >1 to spawn multiple.
			#  <1 to make it a chance.
			#  0 to disable.
			#Range: 0.0 ~ 512.0
			frequency = 0.6375000476837158
			#.
			#Range: > -2147483648
			minHeight = -64
			#.
			#Range: > -2147483648
			maxHeight = 0

		[worldgen.v2.striated_ores_oceans]
			#.
			#Range: > 0
			clusterSize = 32
			#.
			#Amount of clusters generated per Chunk.
			#  >1 to spawn multiple.
			#  <1 to make it a chance.
			#  0 to disable.
			#Range: 0.0 ~ 512.0
			frequency = 0.0416666679084301
			#.
			#Range: > -2147483648
			minHeight = -30
			#.
			#Range: > -2147483648
			maxHeight = 70

		[worldgen.v2.striated_eroded_nether]
			#.
			#Range: > 0
			clusterSize = 24
			#.
			#Amount of clusters generated per Chunk.
			#  >1 to spawn multiple.
			#  <1 to make it a chance.
			#  0 to disable.
			#Range: 0.0 ~ 512.0
			frequency = 0.02083333395421505
			#.
			#Range: > -2147483648
			minHeight = 0
			#.
			#Range: > -2147483648
			maxHeight = 100

		[worldgen.v2.gabbro_blob]
			#.
			#Range: > 0
			clusterSize = 64
			#.
			#Amount of clusters generated per Chunk.
			#  >1 to spawn multiple.
			#  <1 to make it a chance.
			#  0 to disable.
			#Range: 0.0 ~ 512.0
			frequency = 0.6375000476837158
			#.
			#Range: > -2147483648
			minHeight = -64
			#.
			#Range: > -2147483648
			maxHeight = 0

		[worldgen.v2.striated_eroded_overworld]
			#.
			#Range: > 0
			clusterSize = 24
			#.
			#Amount of clusters generated per Chunk.
			#  >1 to spawn multiple.
			#  <1 to make it a chance.
			#  0 to disable.
			#Range: 0.0 ~ 512.0
			frequency = 0.02083333395421505
			#.
			#Range: > -2147483648
			minHeight = -64
			#.
			#Range: > -2147483648
			maxHeight = 0

