
["Feathers' Config"]
	#How many ticks it takes to regenerate half a feather.
	"Feathers Cooldown" = 40
	#How many half feathers each item weighs.
	"Armor Weights Override" = ["item.minecraft.turtle_helmet:2", "item.minecraft.leather_helmet:1", "item.minecraft.leather_chestplate:3", "item.minecraft.leather_leggings:2", "item.minecraft.leather_boots:1", "item.minecraft.chainmail_helmet:2", "item.minecraft.chainmail_chestplate:5", "item.minecraft.chainmail_leggings:4", "item.minecraft.chainmail_boots:1", "item.minecraft.iron_helmet:2", "item.minecraft.iron_chestplate:6", "item.minecraft.iron_leggings:5", "item.minecraft.iron_boots:2", "item.minecraft.diamond_helmet:3", "item.minecraft.diamond_chestplate:8", "item.minecraft.diamond_leggings:6", "item.minecraft.diamond_boots:3", "item.minecraft.golden_helmet:2", "item.minecraft.golden_chestplate:5", "item.minecraft.golden_leggings:3", "item.minecraft.golden_boots:1", "item.minecraft.netherite_helmet:3", "item.minecraft.netherite_chestplate:8", "item.minecraft.netherite_leggings:6", "item.minecraft.netherite_boots:3"]
	#If enabled, armor types have weight, this reduces the amount of feathers you can use based on how heavy your armor is
	"Enable Armor Weights" = true
	#Whether feathers freeze in cold biomes. If they do, they don't regenerate until in a different biome
	"Enable Frost In Cold Biomes" = false
	#Whether the Lightweight enchantment can be enhanted in an enchantment table, or if it is treasure only.
	"Enable Lightweight Enchantment in Table" = true

