#Raids Configurations
#Controls whether the Shogun spawns in raids, usually set to true
shogun_raid_Spawning = true
#Controls whether the Samurai spawns in raids, usually set to true
samurai_raid_Spawning = true
#Controls whether the special Samurai spawns in raids, usually set to true
special_samurai_raid_Spawning = true
#Controls whether the Guard spawns in raids, usually set to true
guard_raid_Spawning = true
#Controls whether the Blastioner spawns in raids, usually set to true
blastioner_raid_Spawning = true
#Controls whether the Royal Guards spawns in raids, usually set to false
royal_guards_raid_Spawning = true
#Controls whether the Cowboy spawns in raids, usually set to true
cowboy_raid_Spawning = false

[Config]
	#Controls the Samurai ai strength, usually set to 1 
	#0 = easy, 1 = normal, 2 = hard, 3 = hardest
	samurai_ai_strength = 1
	#Controls the Shogun ai strength, usually set to 1 
	#0 = easy, 1 = normal, 2 = hard, 3 = hardest
	shogun_ai_strength = 1
	#Controls the Cowboy ai strength, usually set to 1 
	#0 = easy, 1 = normal, 2 = hard, 3 = hardest
	cowboy_ai_strength = 1
	#Controls the Guard ai strength, usually set to 1 
	#0 = easy, 1 = normal, 2 = hard, 3 = hardest
	guard_ai_strength = 1
	#Combat Configurations
	#Controls whether the Shogun takes Griefing Action, usually set to false
	shogun_griefing = false
	#Controls the Shogun Attack Damage Multiplier, usually set to 1 
	#0.35 = easy, 0.7 = normal, 1.5 = hard, 1.9 = hardest
	shogun_attack_multiply = 0.625

["Raid Wave Member Configuration"]
	#    Requires a list of no more and less than 8 integers, each corresponding to its respective wave.
	#
	Shogun_wave_count = [0, 0, 0, 0, 0, 0, 0, 1]
	samurai_wave_counts = [0, 1, 2, 0, 2, 1, 1, 4]
	guard_wave_counts = [0, 1, 1, 0, 2, 1, 1, 2]
	blastioner_wave_counts = [0, 0, 0, 0, 0, 1, 0, 1]
	royal_guards_wave_counts = [0, 1, 0, 0, 1, 0, 1, 1]
	cowboy_wave_counts = [0, 0, 1, 0, 1, 0, 0, 1]

