
[client]
	#If true, the modifications will only apply in creative mode.
	creativeOnly = false
	#When true, a held right click will never place two blocks in a row, the player must move the cursor to a new location.
	forceNewLoc = false
	#When false block placing behaves exactly like vanilla.
	enabled = true

